# Generated by Django 5.0 on 2023-12-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='external_id',
            field=models.CharField(max_length=30),
        ),
    ]
